In [1]:
import torch
import random

sequences = []

for i in range(10):
    seq = torch.zeros(4)
    seq[random.randint(0, 3)] = 1
    sequences.append(seq)

In [ ]:
import sys
sys.path.append('../src')
from VanillaRNN import Model

h_prev = torch.zeros(10)
model = Model(input_size=4, hidden_size=10)
for nucleotide in sequences[0:]:
    h_prev, y = model(nucleotide, h_prev)
    print(y)

tensor([-0.0085, -0.1211,  0.0112,  0.4280,  0.3892, -0.0548,  0.3561,  0.4714,
         0.4297,  0.4233], grad_fn=<TanhBackward0>)
tensor([ 0.4452, -0.4680, -0.5776,  0.2078, -0.1590, -0.4888, -0.0098,  0.0336,
         0.7534, -0.0346], grad_fn=<TanhBackward0>)
tensor([ 0.5351, -0.5526,  0.4374,  0.3919, -0.0599,  0.3065, -0.2206,  0.6096,
         0.0025,  0.4426], grad_fn=<TanhBackward0>)
tensor([ 0.1168, -0.5914, -0.3801,  0.3834,  0.3030,  0.4575,  0.2579,  0.2109,
         0.3501,  0.2001], grad_fn=<TanhBackward0>)
tensor([ 0.6583, -0.7670,  0.2349,  0.5800, -0.0153,  0.2225,  0.2115,  0.7699,
         0.0829,  0.3648], grad_fn=<TanhBackward0>)
tensor([-0.2537, -0.4279, -0.1695,  0.5395,  0.4456,  0.3289,  0.4429,  0.4545,
         0.6288,  0.3014], grad_fn=<TanhBackward0>)
tensor([ 0.3463, -0.7846, -0.6970,  0.0948,  0.2406,  0.0613,  0.0480,  0.4531,
         0.4402,  0.1315], grad_fn=<TanhBackward0>)
tensor([-0.2168, -0.1337,  0.0608,  0.3291,  0.4941,  0.1336,  0.0960,  0.68