In [ ]:
import torch
import numpy as np

In [ ]:
tens_manual = torch.tensor([[1, 2, 3], [4, 5, 6], [6, 7, 8], [9, 10, 11]])
print(tens_manual)
tens_zeros = torch.zeros((4, 3)) #4 rows, 3 columns
print(tens_zeros)
tens_ones = torch.ones((4, 3))
print(tens_ones)
tens_rand = torch.rand((4, 3)) #random values between 0 and 1
print(tens_rand)

#So far tensors are created as columns,rows.

In [ ]:
print(f"Shape of tens_rand: {tens_rand.shape}")
#Shape attribute shows the dimensions of the tensor - rows and columns

In [ ]:
#Can you make a tensor of non-number data types?

non_numeric_tensor = torch.tensor([["apple", "banana"], ["cherry", "date"]])
print(non_numeric_tensor)   

#This will raise an error because PyTorch tensors only support numeric data types.

In [ ]:
#Now try making a tensor from a numpy array
np_array = np.array([[1, 2, 3], [4, 5, 6]])
tensor_from_np = torch.from_numpy(np_array)
print(tensor_from_np)

In [ ]:
#Compare numpy to tensor operations
np_sum = np_array + 10
print(f"Numpy array after adding 10:\n{np_sum}") 
tensor_sum = tensor_from_np + 10
print(f"Tensor after adding 10:\n{tensor_sum}")

#Maths operations are element-wise in both numpy and tensors

Numpy array after adding 10:
[[11 12 13]
 [14 15 16]]
Tensor after adding 10:
tensor([[11, 12, 13],
        [14, 15, 16]])


In [ ]:
#Add tensors together
tens_add = tens_rand + tens_ones
print(f"tens_rand + tens_ones:\n{tens_add}")

#Element-wise addition of two tensors of the same shape
#If shapes differ, an error will occur

tens_multiply = tens_rand * tens_ones
print(f"tens_rand * tens_ones:\n{tens_multiply}")
#Element-wise multiplication of two tensors of the same shape
#If shapes differ, an error will occur

tens_rand + tens_ones:
tensor([[1.6786, 1.1521, 1.8078],
        [1.1509, 1.8856, 1.9220],
        [1.6068, 1.1538, 1.2160],
        [1.6884, 1.1334, 1.8435]])
tens_rand * tens_ones:
tensor([[0.6786, 0.1521, 0.8078],
        [0.1509, 0.8856, 0.9220],
        [0.6068, 0.1538, 0.2160],
        [0.6884, 0.1334, 0.8435]])


In [17]:
#Matrix multiplication
#tens_matmul = torch.matmul(tens_rand, tens_rand)
#print(f"Matrix multiplication of tens_rand with itself:\n{tens_matmul}")
#Matrix multiplication requires multiple tensors
#The number of columns in the first tensor must equal the number of rows in the second tensor
tens_matmul2 = torch.matmul(tens_rand.T, tens_rand)
print(f"Matrix multiplication of transposed tens_rand with tens_rand:\n{tens_matmul2}")

Matrix multiplication of transposed tens_rand with tens_rand:
tensor([[1.3254, 0.4220, 1.3991],
        [0.4220, 0.8489, 1.0851],
        [1.3991, 1.0851, 2.2608]])


In [1]:
import sys
sys.path.append('../src')
from SequenceEncoder import SequenceEncoder

encoder = SequenceEncoder()

# Test 1: Simple encoding
seq = "ACGT"
encoded = encoder.encode(seq)
print(f"Encoded shape: {encoded.shape}")  # Should be (4, 4)
print(f"Encoded:\n{encoded}")

# Test 2: Decoding
decoded = encoder.decode(encoded)
print(f"Decoded: {decoded}")  # Should be "ACGT"
assert decoded == seq, "Encoding/decoding mismatch!"

# Test 3: Lowercase handling
encoded_lower = encoder.encode("acgt")
decoded_lower = encoder.decode(encoded_lower)
print(f"Lowercase test: {decoded_lower}")  # Should be "ACGT"

# Test 4: Invalid character (should raise error)
try:
    encoder.encode("ACGTN")
except ValueError as e:
    print(f"Caught expected error: {e}")

print("\n✅ All tests passed!")

Encoded shape: torch.Size([4, 4])
Encoded:
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
Decoded: ACGT
Lowercase test: ACGT
Caught expected error: Invalid nucleotide: N

✅ All tests passed!
